services:
  - type: worker
    name: assistant-bot
    env: python
    plan: starter
    region: frankfurt
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TZ
        value: Europe/Istanbul

  - type: cron
    name: assistant-news-cron
    env: python
    plan: starter
    region: frankfurt
    branch: main
    schedule: "*/15 * * * *"
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt
    startCommand: python news_cron.py
    envVars:
      - key: TG_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: TZ
        value: Europe/Istanbul
